// Melbourne suburb pronunciation dictionary — seed list.
// Expand from real recordings during July 2026 AU trip (per Refinement 6).
module.exports = {
  'Reservoir':    'REZ-er-vwar',
  'Prahran':      'pra-RAN',
  'Dandenong':    'DAN-de-nong',
  'Tullamarine':  'TULL-a-ma-reen',
  'Pakenham':     'PAY-ken-um',
  'Heidelberg':   'HIGH-del-berg',
  'Werribee':     'WERRY-bee',
  'Point Cook':   'point cook',
  'Tarneit':      'TAR-nate',
  'Craigieburn':  'CRAY-gee-burn',
  'Glen Waverley':'glen WAY-ver-lee',
  'Mount Waverley':'mount WAY-ver-lee',
  'Chadstone':    'CHAD-stun',
  'Brighton':     'BRIGHT-un',
  'Toorak':       'TOO-rak',
  'South Yarra':  'south YAR-ra',
  'Malvern':      'MAL-vurn',
  'Camberwell':   'CAM-ber-well',
  'Armadale':     'ARM-a-dayl',
  'Hawthorn':     'HAW-thorn',
  'Kew':          'kyoo',
  'Footscray':    'FOOT-scray',
  'Coburg':       'CO-burg',
  'Brunswick':    'BRUNS-wick',
  'Richmond':     'RICH-mund',
};
